# Site settings
#theme: Adawolfs
title: A blog about that crazy things I do!
description: A blog about that crazy things I do!
url: https://adawolfs.github.io
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alvin Estrada
user_description: Developer with experience working on Java, Python and Go. DevOps with K8S and Openshift implementations. Speaker at Kubernetes Guatemala
user_title: DevOps & Software Developer
email: adawolfs@gmail.com
twitter_username: adawolfs
github_username:  adawolfs
linkedin_username: alvin-estrada-868b22a5


header-img: assets/img/blog-banner-1.jpg

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

plugins: [jekyll-paginate]


permalink: pretty
paginate: 10
paginate_path: 'blog/page:num'
#destination: _site/blog

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value
